### ISSUE TITLE
Invalid Burn Amount

### ISSUE THREAD

**Issue by cyberguy85** [cyberomanov/ironfish-help#2]
Issue with running burn part of the script. Mint part passed successfully and token are available. 

Creating the transaction: [████████████████████████████████████████] 100% | ETA: 0s
 ›   Error: Request failed (400) validation: Invalid burn amount

/////////////////// [ BURN [ 35% of 00000000 = 0 ] | FAIL | #1 ] ///////////////////

Creating the transaction: [████████████████████████████████████████] 100% | ETA: 0s
 ›   Error: Request failed (400) validation: Invalid burn amount

/////////////////// [ BURN [ 50% of 00000000 = 0 ] | FAIL | #2 ] ///////////////////

Creating the transaction: [████████████████████████████████████████] 100% | ETA: 0s
 ›   Error: Request failed (400) validation: Invalid burn amount

/////////////////// [ BURN [ 39% of 00000000 = 0 ] | FAIL | #3 ] ///////////////////

Creating the transaction: [████████████████████████████████████████] 100% | ETA: 0s
 ›   Error: Request failed (400) validation: Invalid burn amount

/////////////////// [ BURN [ 32% of 00000000 = 0 ] | FAIL | #4 ] ///////////////////

**Comment by cyberomanov** [comment]
yeah, thanks.

fixed in **v1.7**.
